import AppHeader from "@/components/app-header";
import AppSidebar from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SocketProvider } from "@/context/socket.context";
import { UserProvider } from "@/context/user.context";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Chats | Just Chat",
  description: "Generated by create next app",
};

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SocketProvider>
      <UserProvider>
        <SidebarProvider>
          <AppSidebar />

          <main className="w-full overflow-hidden">
            <AppHeader />
            {children}
          </main>
        </SidebarProvider>
      </UserProvider>
    </SocketProvider>
  );
}
